import React, { useState, useRef } from 'react';
import './imageGenerator.css'; // Your styles here
import default_image from '../Assets/default_image.svg'; // Default image

const ImageGenerator = () => {
    const [imageUrl, setImageUrl] = useState(default_image); // Set default image initially
    const inputRef = useRef(null); // Reference to the input field

    // Function to handle image generation using the new URL pattern
    const imageGenerator = async () => {
        const userPrompt = inputRef.current.value;

        if (userPrompt === "") {
            return; // Exit if input is empty
        }

        // Format the URL with the user's input
        const generatedImageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(userPrompt)}`;
        
        // Set the image URL to the one generated by the external service
        setImageUrl(generatedImageUrl);
    };

    return (
        <div className='ai-image-generator'>
            <div className='header'>
                AI Image <span>Generator</span>
            </div>
            <div className='imgLoading'>
                <div className='image-loading'>
                    <div className='image'>
                        <img src={imageUrl} alt="Generated representation" />
                    </div>
                </div>
            </div>
            <div className="search-box">
                <input
                    type="text"
                    className='search-input'
                    placeholder='Describe what you want to see'
                    ref={inputRef}
                />
                <button className="generate-btn" onClick={imageGenerator}>Generate</button> {/* Generate button */}
            </div>
        </div>
    );
}

export default ImageGenerator;
